[phases.setup]
aptPkgs = ["..."]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.build]
cmds = [
    "npm ci",
    "npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"